INFO     [2025-09-07 22:29:05]: APPLICATION RUNNING, probably at http://localhost:5045 - __init__.py:91 
INFO     [2025-09-07 22:29:05]: FLASK_DEBUG: 'True' - __init__.py:93 
INFO     [2025-09-07 22:29:06]: APPLICATION RUNNING, probably at http://localhost:5045 - __init__.py:91 
INFO     [2025-09-07 22:29:06]: FLASK_DEBUG: 'True' - __init__.py:93 
WARNING  [2025-09-07 22:29:06]:  * Debugger is active! - _internal.py:97 
WARNING  [2025-09-07 22:36:17]:  * Debugger is active! - _internal.py:97 
INFO     [2025-09-07 22:36:32]: APPLICATION RUNNING, probably at http://localhost:5045 - __init__.py:91 
INFO     [2025-09-07 22:36:32]: FLASK_DEBUG: 'True' - __init__.py:93 
WARNING  [2025-09-07 22:36:32]:  * Debugger is active! - _internal.py:97 
DEBUG    [2025-09-07 22:36:32]: GET: /  - __init__.py:86 
DEBUG    [2025-09-07 22:36:32]: GET: /favicon.ico  - __init__.py:86 
DEBUG    [2025-09-07 22:36:36]: GET: /  - __init__.py:86 
INFO     [2025-09-07 22:36:55]: APPLICATION RUNNING, probably at http://localhost:5045 - __init__.py:91 
INFO     [2025-09-07 22:36:55]: FLASK_DEBUG: 'True' - __init__.py:93 
WARNING  [2025-09-07 22:36:55]:  * Debugger is active! - _internal.py:97 
DEBUG    [2025-09-07 22:36:55]: GET: /  - __init__.py:86 
DEBUG    [2025-09-07 22:36:55]: we have reached the index - routes.py:11 
INFO     [2025-09-07 22:38:25]: APPLICATION RUNNING, probably at http://localhost:5045 - __init__.py:91 
INFO     [2025-09-07 22:38:25]: FLASK_DEBUG: 'True' - __init__.py:93 
WARNING  [2025-09-07 22:38:25]:  * Debugger is active! - _internal.py:97 
DEBUG    [2025-09-07 22:38:26]: GET: /  - __init__.py:86 
DEBUG    [2025-09-07 22:38:26]: we have reached the index - routes.py:11 
INFO     [2025-09-07 22:38:41]: APPLICATION RUNNING, probably at http://localhost:5045 - __init__.py:91 
INFO     [2025-09-07 22:38:41]: FLASK_DEBUG: 'True' - __init__.py:93 
WARNING  [2025-09-07 22:38:41]:  * Debugger is active! - _internal.py:97 
DEBUG    [2025-09-07 22:38:41]: GET: /  - __init__.py:86 
DEBUG    [2025-09-07 22:38:41]: we have reached the index - routes.py:11 
INFO     [2025-09-07 22:38:53]: APPLICATION RUNNING, probably at http://localhost:5045 - __init__.py:91 
INFO     [2025-09-07 22:38:53]: FLASK_DEBUG: 'True' - __init__.py:93 
WARNING  [2025-09-07 22:38:53]:  * Debugger is active! - _internal.py:97 
DEBUG    [2025-09-07 22:38:53]: GET: /  - __init__.py:86 
DEBUG    [2025-09-07 22:38:53]: we have reached the index - routes.py:11 
INFO     [2025-09-07 22:39:12]: APPLICATION RUNNING, probably at http://localhost:5045 - __init__.py:91 
INFO     [2025-09-07 22:39:12]: FLASK_DEBUG: 'True' - __init__.py:93 
WARNING  [2025-09-07 22:39:12]:  * Debugger is active! - _internal.py:97 
DEBUG    [2025-09-07 22:39:12]: GET: /  - __init__.py:86 
DEBUG    [2025-09-07 22:39:12]: we have reached the index - routes.py:11 
INFO     [2025-09-07 22:39:43]: APPLICATION RUNNING, probably at http://localhost:5045 - __init__.py:91 
INFO     [2025-09-07 22:39:43]: FLASK_DEBUG: 'True' - __init__.py:93 
WARNING  [2025-09-07 22:39:43]:  * Debugger is active! - _internal.py:97 
DEBUG    [2025-09-07 22:39:43]: GET: /  - __init__.py:86 
DEBUG    [2025-09-07 22:39:43]: we have reached the index - routes.py:11 
INFO     [2025-09-07 22:39:55]: APPLICATION RUNNING, probably at http://localhost:5045 - __init__.py:91 
INFO     [2025-09-07 22:39:55]: FLASK_DEBUG: 'True' - __init__.py:93 
WARNING  [2025-09-07 22:39:55]:  * Debugger is active! - _internal.py:97 
DEBUG    [2025-09-07 22:39:55]: GET: /  - __init__.py:86 
DEBUG    [2025-09-07 22:39:55]: we have reached the index - routes.py:11 
